### PR TITLE
Update solidity

### PR DESCRIPTION
**Pull request by andresilva**
Update solidity because of constructor bug in 0.4.22.

### CODE REVIEW

**Review by sorpaas — APPROVED** [review]

**Comment by sorpaas** [comment]
Needs second review on those PRs. Ping @kirushik

**Review by kirushik — APPROVED** [review]
LGTM

**Comment by sorpaas** [comment]
It looks like Github is broken -- although all tests pass, it still shows "required statuses must pass before merging"...

**Comment by kirushik** [comment]
@sorpaas Yep, looks like the "required checks" setting in admin panel is out of touch with reality.
I've disabled those for now — let's merge this and I'll re-check the status in a couple of days.

**Pull request merged**
